Repository garden-share-08/garden-share-fe, pull requests merged in 2021-02, with the labels that each got.

#16 Feature connect redux
  src/components/app/App.js
  src/components/form/Form.js
  src/components/form/Form.scss
  src/components/homePage/HomePage.js
  src/components/productCard/ProductCard.js
  src/components/productPage/ProductPage.js
  src/mockData/mockData.js
  src/mockData/mockListing.js
  src/redux/actions/actions.js
  src/redux/reducers/allListings.js
  src/redux/reducers/index.js
  src/redux/reducers/productPage.js
Labels: FE, enhancement

#19 Feature form functionality
  .travis.yml
  src/components/Login/Login.js
  src/components/Login/Login.test.js
  src/components/SignUp/SignUp.js
  src/components/SignUp/SignUp.test.js
  src/components/app/App.js
  src/components/app/App.test.js
  src/components/form/Form.js
  src/components/form/Form.test.js
  src/components/homePage/HomePage.test.js
  src/components/listing/Listing.test.js
  src/components/myListings/MyListings.test.js
  src/components/myOffers/MyOffers.test.js
  src/components/navBar/NavBar.test.js
  src/components/newListing/NewListing.test.js
  src/components/newListingPage/NewListingPage.js
  src/components/newListingPage/NewListingPage.test.js
  src/components/productCard/ProductCard.test.js
  src/components/productPage/ProductPage.js
  src/components/productPage/ProductPage.test.js
  src/components/profile/Profile.test.js
  src/components/userListing/userListing.test.js
  src/components/userOffer/UserOffer.test.js
  src/redux/actions/actions.js
  src/redux/reducers/index.js
  src/redux/reducers/userOffers.js
Labels: FE, MVP, enhancement

#21 Feature navbar styling
  src/components/navBar/NavBar.js
  src/components/navBar/NavBar.scss
  src/images/GardenShareLogo.png
Labels: React, SASS Styling

#22 Feature profile
  src/components/app/App.js
  src/components/myListings/MyListings.js
  src/components/myOffers/MyOffers.js
  src/components/profile/Profile.js
  src/components/userListing/userListing.js
  src/components/userOffer/UserOffer.js
  src/mockData/mockUserListings.js
  src/mockData/mockUserOffer.js
  src/redux/actions/actions.js
  src/redux/reducers/index.js
  src/redux/reducers/userListings.js
Labels: FE, MVP

#24 Feature testing setup
  src/components/Login/Login.test.js
  src/components/SignUp/SignUp.test.js
  src/components/app/App.test.js
  src/components/form/Form.test.js
  src/components/homePage/HomePage.js
  src/components/homePage/HomePage.test.js
  src/components/listing/Listing.test.js
  src/components/myListings/MyListings.test.js
  src/components/myOffers/MyOffers.test.js
  src/components/navBar/NavBar.js
  src/components/navBar/NavBar.test.js
  src/components/newListing/NewListing.test.js
  src/components/newListingPage/NewListingPage.test.js
  src/components/productCard/ProductCard.js
  src/components/productCard/ProductCard.test.js
  src/components/productPage/ProductPage.test.js
  src/components/profile/Profile.test.js
  src/components/userListing/userListing.js
  src/components/userListing/userListing.test.js
  src/components/userOffer/UserOffer.test.js
Labels: Testing

#27 Feature profile style
  src/components/homePage/HomePage.js
  src/components/myListings/MyListings.js
  src/components/myListings/MyListings.scss
  src/components/myOffers/MyOffers.js
  src/components/myOffers/MyOffers.scss
  src/components/navBar/NavBar.scss
  src/components/profile/Profile.js
  src/components/profile/Profile.scss
  src/components/userListing/userListing.js
  src/components/userListing/userListing.scss
  src/components/userOffer/UserOffer.js
  src/components/userOffer/UserOffer.scss
  src/sass/_mixins.scss
  src/sass/_variables.scss
Labels: FE, enhancement

#32 Feature user authentication
  package-lock.json
  package.json
  src/components/Login/Login.js
  src/components/app/App.js
  src/components/homePage/HomePage.js
  src/components/logout/Logout.js
  src/components/navBar/NavBar.js
  src/components/productPage/ProductPage.js
  src/components/userInfo/UserInfo.js
  src/index.js
  src/redux/actions/actions.js
  src/redux/reducers/allListings.js
  src/redux/reducers/index.js
  src/redux/reducers/loginUser.js
  src/redux/store.js
Labels: FE, Redux, enhancement

#34 Feature style product page
  package-lock.json
  src/components/form/Form.js
  src/components/form/Form.scss
  src/components/logout/Logout.js
  src/components/logout/Logout.scss
  src/components/myListings/MyListings.js
  src/components/navBar/NavBar.scss
  src/components/newListingPage/NewListingPage.js
  src/components/newListingPage/NewListingPage.scss
  src/components/productPage/ProductPage.js
  src/components/productPage/ProductPage.scss
Labels: SASS Styling, enhancement

#45 Feature api calls
  src/components/form/Form.js
  src/components/homePage/HomePage.js
  src/components/myOffers/MyOffers.js
  src/components/myOffers/MyOffers.scss
  src/components/productCard/ProductCard.js
  src/components/productPage/ProductPage.js
  src/components/userListing/userListing.js
  src/components/userListing/userListing.test.js
  src/components/userOffer/UserOffer.js
  src/components/userOffer/UserOffer.scss
  src/redux/actions/actions.js
  src/redux/reducers/index.js
  src/redux/reducers/loginUser.js
  src/redux/reducers/offer.js
  src/redux/reducers/productPage.js
  src/redux/reducers/userOffers.js
Labels: FE, Redux, enhancement
