Repository garden-share-08/garden-share-fe, pull requests merged in 2021-03, with the labels that each got.

#48 Add styling to homepage view
  src/components/homePage/HomePage.js
  src/components/homePage/HomePage.scss
  src/components/productCard/ProductCard.js
  src/components/productCard/ProductCard.scss
  src/components/productPage/ProductPage.js
  src/sass/_mixins.scss
Labels: enhancement

#54 Feature cookies
  package-lock.json
  package.json
  src/components/app/App.js
  src/components/form/Form.js
  src/components/form/Form.scss
  src/components/homePage/HomePage.js
  src/components/myListings/MyListings.js
  src/components/myOffers/MyOffers.js
  src/components/newListingPage/NewListingPage.js
  src/components/productPage/ProductPage.js
  src/components/productPage/ProductPage.scss
  src/components/profile/Profile.js
  src/components/userListing/userListing.js
  src/components/userOffer/UserOffer.js
  src/index.js
  src/redux/actions/actions.js
  src/redux/reducers/offer.js
  src/redux/reducers/userListings.js
Labels: enhancement

#56 Testing redux
  src/redux/reducers/allListings.test.js
  src/redux/reducers/loginUser.test.js
  src/redux/reducers/offer.test.js
  src/redux/reducers/productPage.test.js
  src/redux/reducers/userListing.test.js
  src/redux/reducers/userOffers.test.js
Labels: Redux, Testing

#57 Style Login Page
  src/components/Login/Login.js
  src/components/Login/Login.scss
  src/images/GardenShareLogo.png
Labels: SASS Styling, enhancement

#58 Feature login render
  package-lock.json
  src/components/Login/Login.js
  src/components/SignUp/SignUp.js
  src/components/SignUp/SignUp.scss
  src/components/SignUp/SignUp.test.js
  src/components/app/App.js
  src/components/homePage/HomePage.js
  src/components/listing/Listing.js
  src/components/listing/Listing.scss
  src/components/listing/Listing.test.js
  src/components/myListings/MyListings.js
  src/components/myOffers/MyOffers.js
  src/components/navBar/NavBar.js
  src/components/navBar/NavBar.scss
  src/components/newListing/NewListing.js
  src/components/newListing/NewListing.scss
  src/components/newListing/NewListing.test.js
  src/components/productPage/ProductPage.js
Labels: enhancement

#59 Work on async bugs for accept/decline buttons
  .travis.yml
  package-lock.json
  package.json
  src/components/app/App.js
  src/components/form/Form.js
  src/components/homePage/HomePage.js
  src/components/myListings/MyListings.js
  src/components/myOffers/MyOffers.test.js
  src/components/userListing/userListing.js
Labels: FE, MVP, React, Redux, bug
